accounts/urls.py
from django.conf.urls import *
from django.contrib.auth.views import login, logout

urlpatterns = patterns(
    '',
    url(r'^login/$', login, {'template_name':'accounts/login.html'},name='login'), 
    url(r'^logout/$', logout, {'next_page':'/list'},name='logout'), 
    url(r'^register/$', 'accounts.views.registration',name='register'), 
)

assignment1/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from todo import views
from todo.models import Todo
from django.views.generic import ListView, DetailView

urlpatterns = patterns('',

    #url(r'^todo/(?P<todo_id>\d+)$', views.todo_detail, name="detail"),
    url(r'^listall/$', ListView.as_view(model=Todo), name='todo_listall'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^list/(?P<folder>.*)$', views.TodoList.as_view(), name='todo_list'),
    url(r'^tag/(?P<tags>.*)$', views.TodoByTag.as_view(), name='todo_list'),
    #url(r'^detail/(?P<pk>\d+)$', DetailView.as_view(model=Todo), name='detail'),
    url(r'^add/$', views.MyView.as_view(), name='todo_add'),
    url(r'^todo/(?P<pk>\d+)/edit/$', views.TodoUpdate.as_view(),  name='todo_update'),
    url(r'^todo/(?P<pk>\d+)$', views.TodoDetail.as_view(),  name='detail'),
    url(r'^todo/(?P<pk>\d+)/delete/$', views.TodoDelete.as_view(),  name='todo_delete'),
)

todo/models.py
from django.db import models
from django.core.urlresolvers import reverse
from accounts.models import UserProfile

# Create your models here
class Todo(models.Model):
    user = models.ForeignKey(UserProfile, blank=True, null=True)
    title = models.CharField(max_length=225)
    content = models.TextField(blank=True) #not a required field
    due = models.DateTimeField(null=True, blank=True) #due datetime is optional
    created = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)
    done = models.BooleanField(default=False)
    #folder is optional
    folder = models.ForeignKey('Folder', related_name= "things", null=True, blank=True)
    #tag is optional
    tag = models.ManyToManyField('Tag', related_name='things', null=True, blank=True)
    
    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse("detail", kwargs={"pk":self.pk})
        

class Folder(models.Model):
    title = models.CharField(max_length=255)
    
    def __str__(self):
        return self.title
        
class Tag(models.Model):
    title = models.CharField(max_length=255)
    
    def __str__(self):
        return self.title
    

todo/forms.py
from django import forms
from .models import Todo, Folder, Tag
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Hidden, Button, HTML, Div, Field, Row, Fieldset


class TodoForm(forms.ModelForm):
    class Meta: 
        model = Todo
        fields = '__all__'
        
    
    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "todoform"
        
        #Create a new folder select list, with added css and style codes
        folder = Div('folder', css_class="col-xs-12", style="padding:0px;") 
        self.helper.layout.pop(6) #remove the original folder select list 
        #Insert new folder select list with a "Create New Folder" button as a Fieldset
        self.helper.layout.insert(6,Fieldset("Select folder",folder, Button("createfoldermodal", value="Create New Folder", css_class="btn btn-primary btn-sm col-xs-12 ", data_toggle="modal", data_target="#myModal")))
        
        #Create a new tag multi-select list, with added css and style codes
        tag = Div('tag',css_class = "col-xs-12", style="padding:0px;") 
        #oldtagselect = self.helper.layout.pop(7) #remove the original tag multi-select list
        #Insert new tag multi-select list with a "Create New Tag" button as a Fieldset
        self.helper.layout.insert(7, Fieldset("Select Tag",tag, Button("createtagmodal", value="Create New Tag", css_class="btn btn-primary btn-sm col-xs-12", data_toggle="modal", data_target="#myModal2")))
        
        #Create a "Create New Note" button 
        self.helper.layout.append(Button('btn_createtodo', 'Create Todo', css_class='createtodo', style="margin-top:15px;"))
        #Add a hidden field 'btn_createnote' so that it will be submitted together in the form to allow server side to 'know'
        #that this button has been clicked
        self.helper.layout.append(Hidden(name='btn_createtodo', value="btn_createtodo"))
        
        
        
    def full_clean(self):
        #http://stackoverflow.com/questions/4340287/override-data-validation-on-one-django-form-element
        super(TodoForm, self).full_clean()
        if 'tag' in self._errors:
            self.cleaned_data['tag'] = []
            print("remove tag errors")
            del self._errors['tag']
            
class TodoFormUpdate(forms.ModelForm):
    class Meta: 
        model = Todo
        #fields = '__all__'
        exclude = ['user']
        
    def __init__(self, *args, **kwargs):
        super(TodoFormUpdate, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "todoformupdate"
        
        self.helper.add_input(Submit('submit', 'Update'))
            
class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super(FolderForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "folderform"
        self.helper.layout.append(Hidden(name='btn_createfolder', value="btn_createfolder"))
        self.helper.layout.append(Button('btn_createfolder', 'Create Folder', css_class='createfolder', data_dismiss="modal"))
        

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super(TagForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = "tagform"
        self.helper.layout.append(Hidden(name='btn_createtag', value="btn_createtag"))
        self.helper.layout.append(Button('btn_createtag', 'Create Tag', css_class='createtag', data_dismiss="modal"))

todo/views.py
import json

from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from .models import Todo
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from todo.forms import TodoForm
from django.conf.urls import url
from django.db.models import Q
from .models import Todo, Folder, Tag
from .forms import TodoForm, FolderForm, TagForm, TodoFormUpdate
from django.views.generic import DetailView, ListView, TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.serializers.json import DjangoJSONEncoder
from accounts.models import UserProfile

# Create your views here.

    
class TodoList(ListView): 
    model = Todo
    queryset = Todo.objects.all()

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TodoList, self).dispatch(*args, **kwargs)
    
    def get_queryset(self):
        #self.request.user will contain the "User" object, however,
        #user field in the Todo model is an instance of "UserProfile" object
        #So need to ensure that when we filter all the user owned todos, we
        #filter using the 'correct' UserProfile instance based on logged in "User" object 
        #in self.request.user
        curruser = UserProfile.objects.get(user=self.request.user)
        folder = self.kwargs['folder']
        if folder == '':
            #filter based on current logged in user
            self.queryset = Todo.objects.filter(user=curruser)
            return self.queryset
        else:
            #filter based on current logged in user
            self.queryset = Todo.objects.all().filter(user=curruser).filter(folder__title__iexact=folder)
            return self.queryset
    
    def get_context_data(self, **kwargs):
        context = super(TodoList, self).get_context_data(**kwargs)
        context['total'] = self.queryset.count()
        #provided so that the avatar can be displayed in base.html
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context


class TodoDetail(DetailView):
    model = Todo
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TodoDetail, self).dispatch(*args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super(TodoDetail, self).get_context_data(**kwargs)
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context

class TodoUpdate(UpdateView):
    model = Todo
    form_class = TodoFormUpdate
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TodoUpdate, self).dispatch(*args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super(TodoUpdate, self).get_context_data(**kwargs)
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context
    
class TodoByTag(ListView):
    model = Todo
    
    queryset = Todo.objects.all()
    def get_queryset(self):
        tags = self.kwargs['tags']
        pieces = tags.split('/') #extract different tags separated by /
        
        queries = [Q(tag__title__iexact=value) for value in pieces]
        # Take one Q object from the list
        query = queries.pop()
        # Or the Q object with the ones remaining in the list
        for item in queries:
            query |= item
        # Query the model
        curruser = UserProfile.objects.filter(user=self.request.user) #only query todos by curruser
        alltodos = Todo.objects.filter(user=curruser).filter(query).distinct().order_by('tag__title')
        self.queryset = alltodos #Setting the queryset to allow get_context_data to apply count
        return alltodos
    
    def get_context_data(self, **kwargs):
        context = super(TodoByTag, self).get_context_data(**kwargs)
        context['total'] = self.queryset.count()
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context


class MyView(TemplateView):
    folder_form_class = FolderForm
    tag_form_class = TagForm
    todo_form_class = TodoForm
    template_name = "todo/todo_hybrid.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MyView, self).dispatch(*args, **kwargs)
        
    def get(self, request, *args, **kwargs):
        kwargs.setdefault("createfolder_form", self.folder_form_class())
        kwargs.setdefault("createtag_form", self.tag_form_class())
        kwargs.setdefault("createtodo_form", self.todo_form_class())
        #Added curruser so that profile picture of curruser can be rendered.
        kwargs.setdefault('curruser', UserProfile.objects.get(user=self.request.user))
        return super(MyView, self).get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        form_args = {
            'data': self.request.POST,
        }
        
        if "btn_createfolder" in request.POST['form']:
            form = self.folder_form_class(**form_args)
            if not form.is_valid():
                return self.get(request,
                                   createfolder_form=form)
            else:
                form.save()
                data = Folder.objects.all()
                result_list = list(data.values('id','title'))
                return HttpResponse(json.dumps(result_list, cls=DjangoJSONEncoder))
        elif "btn_createtag" in request.POST['form']:
            form = self.tag_form_class(**form_args)
            if not form.is_valid():
                return self.get(request,
                                   createtag_form=form)
            else:
                form.save() #save the new object
                data = Tag.objects.all() # retrieve all records
                result_list = list(data.values('id','title'))
                return HttpResponse(json.dumps(result_list, cls=DjangoJSONEncoder)) #return to ajax as success with all the new records.
        elif "btn_createtodo" in request.POST['form']:
            form = self.todo_form_class(**form_args)
            if not form.is_valid():
                return self.get(request,
                                   createtodo_form=form) 
            else:
                try:
                    #Find out which user is logged in and get the correct UserProfile record.
                    curruser = UserProfile.objects.get(user=self.request.user)
                    obj = form.save(commit=False)
                    obj.user = curruser #Save the todo todo under that user
                    obj.save() #save the new object
                    
                except Exception, e:
                    print("errors" + str(e))
                response = {'status': 1, 'message':'ok'}
                return HttpResponse(json.dumps(response, cls=DjangoJSONEncoder)) #return to ajax as success with all the new records.
            
        return super(MyView, self).get(request)
    

class TodoDelete(DeleteView):
    model = Todo
    success_url = '/list/'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TodoDelete, self).dispatch(*args, **kwargs)
        
    def get_context_data(self, **kwargs):
        context = super(TodoDelete, self).get_context_data(**kwargs)
        context['curruser'] = UserProfile.objects.get(user=self.request.user)
        return context

todo/templates/todo/base.html
{# Load the tag library #}
{% load bootstrap3 %}

<head>
  <title>
    {%block title%}
    {%endblock%}
  </title>
</head>
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script type="text/css">
.mynavbar {
    display:block;
    margin:0px;
    padding:0px;
    height:50px;
}

</script>
<script type="text/javascript">
    $(document).ready(function() {
        jQuery.ajaxSettings.traditional = true; //Important 
        
        /*Important functions to enable CSRF token as Django requires it*/
        function getCookie(name) {
            var cookieValue = null;
            var i = 0;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (i; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
    
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        /*end CSRF token */
    
        /*Setting the format of the datepicker and datetimepicker*/
        $('.dateinput').datepicker({
            format: "yyyy/mm/dd"
        });
        $('.datetimeinput').datetimepicker({
            format: "YYYY-MM-DD HH:mm"
        });
    
       
        $('.createfolder').click(function(e) {
            
            formid = $(this).parent().attr("id"); //find the formid of the button pressed via parent 
            
            $.ajax({
                type: "POST",
                url: "/add/",
                dataType: "json",
                data: {
                    "title": $("#" + formid + " #id_title").val(),
                    "color": $("#" + formid + " #id_color").val(),
                    "fontcolor": $("#" + formid + " #id_fontcolor").val(),
                    "form": $("#" + formid).serialize(),
    
                },
                success: function(data, status) {
                    //Populate the dropdown list with all the folders returned in json
                    var $el = $("#id_folder");
                    $el.empty(); // remove old options
                    $el.append($("<option></option>").attr("value", "").text("---------"));
                    $.each(data, function(key, value) {
                        $el.append($("<option></option>").attr("value", value.id).text(value.title));
                    });
                },
                crossDomain: false, // obviates need for sameOrigin test
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
        
        $('.createtag').click(function(e) {
            formid = $(this).parent().attr("id"); //find the formid of the button pressed via parent 
            
            $.ajax({
                type: "POST",
                url: "/add/",
                dataType: "json",
                data: {
                    "title": $("#" + formid + " #id_title").val(),
                    "color": $("#" + formid + " #id_color").val(),
                    "fontcolor": $("#" + formid + " #id_fontcolor").val(),
                    "form": $("#" + formid).serialize(),
    
                },
                success: function(data, status) {
                    //Populate the dropdown list with all the folders returned in json
                    var $el = $("#id_tag");
                    $el.empty(); // remove old options
                    $.each(data, function(key, value) {
                        $el.append($("<option></option>").attr("value", value.id).text(value.title));
                    });
                },
                crossDomain: false, // obviates need for sameOrigin test
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
        
        $('.btn.createtodo').click(function(e) {
            
            formid = $(this).parent().attr("id"); //find the formid of the button pressed via parent 
    
            $.ajax({
                type: "POST",
                url: "/add/",
                dataType: "json",
                data: {
                     "title": $("#" + formid + " #id_title").val(),
                     "done": $("#" + formid + " #id_done").prop("checked"),
                     "content": $("#" + formid + " #id_content").val(),
                     "due": $("#" + formid + " #id_due").val(),
                     "color": $("#" + formid + " #id_color").val(),
                     "fontcolor": $("#" + formid + " #id_fontcolor").val(),
                     "folder": $("#" + formid + " #id_folder").val(),
                     "tag": $("#" + formid + " #id_tag").val(),
                     "form": $("#" + formid).serialize(),
    
                },
                success: function(data) {
                    if (data.status == 1){
                        //alert(data.message)
                        //http://stackoverflow.com/questions/503093/how-can-i-make-a-redirect-page-using-jquery
                        window.location.replace("/list") //to redirect to another page
                    }
                },
                crossDomain: false, // obviates need for sameOrigin test
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type)) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        });
        
        /* To reset the modal input fields when modal is closed.*/
        $('#myModal').on('hidden.bs.modal', function(){
            $(this).find('form')[0].reset();
        });
        /* To reset the modal input fields when modal is closed.*/
        $('#myModal2').on('hidden.bs.modal', function(){
            $(this).find('form')[0].reset();
        });
    });
</script>
</head>
<body>
<div class="mynavbar">
        <ul class="nav nav-tabs navbar-right">
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">
                  {%if user.is_authenticated%}
                      <img src="/media/{{curruser.picture}}" height="30px" %} />
                      Hi {{user.username}}!
                  {%else%}
                      Login here!
                  {%endif%}
                  
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  {%if user.is_authenticated%}
                      <li><a href="/accounts/logout">Logout</a></li>
                      <li><a href="/add">Add a new todo</a></li>
                      <li><a href="/list">View all my todos</a></li>
                  {%else%}
                      <li><a href="/accounts/login">Login</a></li>
                  {%endif%}
                
                      
                </ul>
              </li>
            </ul>
        <!--</div>-->
    <!--</div>-->
</div>
{%block content%}

{%endblock%}
</body>

todo/templates/todo/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}" />
{% if things %}
    <div class="wrap">
        <div class="header"><span>Todo List</span></div>
            <div class="wrap-list">
                <ol class="list">
                    {% for thing in things %}
                            <li>
                            <a href={% url 'detail' thing.id %}>
                            <input type="checkbox" thing.id >
                            <label for=thing.id> {{thing.title}}</label></a>
                            </li>
                            {%endfor%}
                </ol>
            </div> 
    </div>        
{% else %}
    <p>There is nothing left to do.</p>
{% endif %}

todo/templates/todo/todo_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

todo/templates/todo/todo_detail.html
{%extends 'todo/base.html'%}
{%block title%}
    Note - {{object.title}}
{%endblock%}
{%block content%}
    <div class="container">
        <h4>Title</h4> 
        <p>{{object.title}}</p>
        <h4>Content</h4>
        <p>{{object.content}}</p>
        <h4>Folder</h4>
        <p>{{object.folder}}</p>
        <h4>Tag(s):</h4>
                <ul>
                <!--https://docs.djangoproject.com/en/1.7/ref/templates/builtins/#for-->
                {%for t in object.tag.all%}
                    <li>{{t.title}}</li>
                {%endfor%}
                </ul>
    </div>
{%endblock%}

todo/templates/todo/todo_form.html
{%extends 'todo/base.html'%}
{% load crispy_forms_tags %}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
    <!--distinguish between update or create view-->
    <!--http://stackoverflow.com/questions/18806703/within-a-template-distinguish-between-create-and-update-form-->
    {%if object%}
        <h1>Update {{object.title}}</h1>
    {%else%}
        <h1>Create a New Note</h1>
    {%endif%}
    {% crispy form %}
	</div>
     </div>
</div>
{%endblock%}

todo/templates/todo/todo_hybrid.html
{%extends 'todo/base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<div id="mymessage" class="form-group alert-danger">
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Create a new todo</h3>
            {%if createtodo_form %}
                {%crispy createtodo_form %}
            {%endif%}
            
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Create New Folder</h4>
                  </div>
                  <div class="modal-body">
                    <!--MODAL ADD FOLDER-->
                    {%if createfolder_form%} {% crispy createfolder_form %} {%endif%}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Create New Tag</h4>
                  </div>
                  <div class="modal-body">
                    {%if createtag_form%} {% crispy createtag_form %} {%endif%}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>

        </div>
    </div>
</div>
{%endblock%}

todo/templates/todo/todo_list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}" />
<h2> Total number of things to do: {{total}} </h2>
{% if object_list %}
    <div class="wrap">
        <div class="header"><span>Todo List</span></div>
            <div class="wrap-list">
                <ol class="list">
                    {% for thing in object_list %}
                            <li>
                            <a href={% url 'detail' thing.id %}>
                            <input type="checkbox" thing.id >
                            <label for=thing.id> {{thing.title}}</label></a>
                            </li>
                            {%endfor%}
                </ol>
            </div> 
    </div>        
{% else %}
    <p>There is nothing left to do.</p>
{% endif %}